// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASkmI6Qv6V-t6KfpXeXFcEFd3xX1it6GQ',
    appId: '1:453318196912:web:1d78f9014ea2d907464575',
    messagingSenderId: '453318196912',
    projectId: 'sferatz',
    authDomain: 'sferatz.firebaseapp.com',
    databaseURL: 'https://sferatz-default-rtdb.firebaseio.com',
    storageBucket: 'sferatz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCufsRUJE8L9M7_pngwDQmTe3_krYgyKVA',
    appId: '1:453318196912:android:2d8aee96f778b7c8464575',
    messagingSenderId: '453318196912',
    projectId: 'sferatz',
    databaseURL: 'https://sferatz-default-rtdb.firebaseio.com',
    storageBucket: 'sferatz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZbNPc67A9SR1iXXOLG6k4jVbWeNPN80I',
    appId: '1:453318196912:ios:e30d6dff8d25b75f464575',
    messagingSenderId: '453318196912',
    projectId: 'sferatz',
    databaseURL: 'https://sferatz-default-rtdb.firebaseio.com',
    storageBucket: 'sferatz.appspot.com',
    iosClientId: '453318196912-of6a7bmnsjgj3lgn25hnip8a5dne3hrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.sferatz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZbNPc67A9SR1iXXOLG6k4jVbWeNPN80I',
    appId: '1:453318196912:ios:e30d6dff8d25b75f464575',
    messagingSenderId: '453318196912',
    projectId: 'sferatz',
    databaseURL: 'https://sferatz-default-rtdb.firebaseio.com',
    storageBucket: 'sferatz.appspot.com',
    iosClientId: '453318196912-of6a7bmnsjgj3lgn25hnip8a5dne3hrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.sferatz',
  );
}
